name: Deploy Supabase Edge Functions
on:
  push:
    paths:
      - 'functions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Deploy Start Translation Function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          deno install -A -f --unstable -n supabase https://deno.land/x/supabase_cli@latest/cli.ts
          supabase functions deploy start_translation --project-ref $SUPABASE_PROJECT_REF --token $SUPABASE_ACCESS_TOKEN

      - name: Deploy Process Translation Function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          supabase functions deploy process_translation --project-ref $SUPABASE_PROJECT_REF --token $SUPABASE_ACCESS_TOKEN